### ISSUE TITLE
Auth settings

### ISSUE THREAD

**Issue by TomCrowley** [cdeng/angularFire-survey#1]
Don't you need to include the proper security and rules in the set-up Readme? I am getting an auth error.

**Comment by cdeng** [comment]
What was the error you've encountered?  Detailed error message would be helpful.

**Comment by TomCrowley** [comment]
"Error: permission_denied: Client doesn't have permission to access the desired data."
You can see it in the Javascript console here: https://scorching-heat-4406.firebaseapp.com/#/survey

In the  configuration section ( https://github.com/cdeng/angularFire-survey#configuration ) it seems like you would need the proper Firebase Rules for the Security & Rules section in the Firebase Admin pages.

Here: http://puu.sh/i23l9/70b237ec7a.png

**Comment by cdeng** [comment]
Is your Email & Password Authentication enabled in your firebase database?
![image](https://cloud.githubusercontent.com/assets/4248581/7828793/67eb4332-0406-11e5-8454-3834fd285264.png)

**Comment by TomCrowley** [comment]
Yes it is enabled. I really think it is related to the missing configuration information for  Security & Rules.

**Comment by cdeng** [comment]
The demo site is using default security and rules settings as following.

```
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
```

I am looking at your site and seeing invalid password error.  Try to check and reset the password you set in Firebase and make it match with configuration in your code.

**Comment by TomCrowley** [comment]
It works now. I suggest you add that to the configuration section. I had already been playing with my firebase environment so it did not have the default security setting.
