### ISSUE TITLE
how to start?

### ISSUE THREAD

**Issue by officerebel** [cdeng/angularFire-survey#3]
I have put credentials in firebase but how to get this angular running?

**Comment by cdeng** [comment]
Hello,

If you have followed the [configuration instructions](https://github.com/cdeng/angularfire-survey#configuration), then just start a web server from app directory and you should be all set.

Let me know if you have any further questions.

Thanks,
-Cheng

**Comment by officerebel** [comment]
Hi thanx! Wich server? ng start worked. 

npm install -g angular-cli 

ng serve
open http://localhost:4200


also followed https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md but now it does not work anymore.
Can you help with the commands?
Tim

**Comment by cdeng** [comment]
Hi Tim,
The only thing you have to do is launching a development web server.  There are many ways to start a web server.  Using "ng serve" as you mentioned is one of them. Here are some other ways to serving any directory - [How to easily start a webserver in any folder?](http://askubuntu.com/questions/377389/how-to-easily-start-a-webserver-in-any-folder) You don't have to follow that angularfire setup processes.
Thanks,
-Cheng

**Comment by officerebel** [comment]
When i use ng serve I see "app works" but not the angular survey.

**Comment by cdeng** [comment]
Well, you have to tweak a few things in order to use CLI tool for Angular.  However, launching a web development server is the easiest way to run most JS apps from GitHub.  I would suggest you to refer to this question and solution - [How to easily start a webserver in any folder?](http://askubuntu.com/questions/377389/how-to-easily-start-a-webserver-in-any-folder).  Besides that, if you are using a IDE (e.g. NetBeans, IntelliJ), they usually have a simple "Run Project" or "Run this Application" button that starts a web server automatically in one click.

**Comment by officerebel** [comment]
Hi Thanx for your help but it does not work. Also put it in mamp and it does not work. Wich commands do you use?

**Comment by cdeng** [comment]
What error messages are you getting?  

I usually use "Run Project" function in IDEs for running these kinds of apps, but I am sure ```python -m SimpleHTTPServer 8000``` will work if you have Python installed and running this command in the project directory.

**Comment by officerebel** [comment]
I get a white screen

**Comment by cdeng** [comment]
Did you see any error messages in console? Did you run the web server in the project directory?

**Comment by officerebel** [comment]
127.0.0.1 - - [20/Dec/2016 22:40:06] "GET /app/js/directives.js HTTP/1.1" 200 -
in terminal I see

**Comment by cdeng** [comment]
That's a good sign, but I would like you to look at the debugging console.  Normally, you activate debugging in your browser with F12, and select "**Console**" in the debugger menu.  Chrome would be best if you have it installed.

**Comment by officerebel** [comment]
ncaught ReferenceError: angular is not defined
    at main.js:10
angular.js:4640 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=myApp&p1=Error%3A%2…3A%2F%2Flocalhost%3A8000%2Fapp%2Flib%2Fangular%2Fangular.min.js%3A21%3A179)
    at angular.js:38
    at angular.js:4640
    at q (angular.js:321)
    at g (angular.js:4601)
    at cb (angular.js:4523)
    at c (angular.js:1758)
    at Bc (angular.js:1779)
    at fe (angular.js:1664)
    at angular.js:31763
    at HTMLDocument.b (angular.js:3207)

**Comment by cdeng** [comment]
That doesn't make any sense.  This project doesn't have the main.js file.  What are you using for the web server?  Are you pointing the web server at the right directory?

**Comment by officerebel** [comment]
i wrote this code inside the directory. python -m SimpleHTTPServer 8000 how to put the web server to another directory?

**Comment by cdeng** [comment]
Go to the directory you want and run the python simple http server from that directory.

**Comment by officerebel** [comment]
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=myApp&p1=Error%3A%2…2F%2Flocalhost%3A8000%2Fapp%2F%2Flib%2Fangular%2Fangular.min.js%3A21%3A179)
    at angular.js:38
    at angular.js:4640
    at q (angular.js:321)
    at g (angular.js:4601)
    at cb (angular.js:4523)
    at c (angular.js:1758)
    at Bc (angular.js:1779)
    at fe (angular.js:1664)
    at angular.js:31763
    at HTMLDocument.b (angular.js:3207)

**Comment by cdeng** [comment]
Which file does this error complains about? It looks the same as the error you got last time. Make sure you are looking at the right directory.

**Comment by officerebel** [comment]
it works ;-) thanx! any tips on how to upload to server with use of terminal commands after finished

**Comment by cdeng** [comment]
It depends on which host you'd like to use.  I would suggest to start with free hosts like [Firebase Hosting](https://firebase.google.com/docs/hosting/) or [GitHub Pages](https://pages.github.com/) if you don't have a host.

**Comment by officerebel** [comment]
great support Thanx! Ps where to edit the css?In main css or bootstrap theme?

**Comment by cdeng** [comment]
[app/css/main.css](https://github.com/cdeng/angularfire-survey/blob/master/app/css/main.css)
